"""Prompt templates for LLM Visibility."""

from .company_profile import COMPANY_PROFILE_SYSTEM_PROMPT, COMPANY_PROFILE_USER_PROMPT
from .customer_prompts import CUSTOMER_PROMPTS_SYSTEM_PROMPT, CUSTOMER_PROMPTS_USER_PROMPT

__all__ = [
    "COMPANY_PROFILE_SYSTEM_PROMPT",
    "COMPANY_PROFILE_USER_PROMPT",
    "CUSTOMER_PROMPTS_SYSTEM_PROMPT",
    "CUSTOMER_PROMPTS_USER_PROMPT"
]
